name: flutter_application_proj2cp
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_screenutil: ^5.9.0
  get: ^4.6.1
  smooth_page_indicator: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.1
  flutter_cache_manager: ^3.3.1
  sqflite: ^2.3.3
  shared_preferences: ^2.2.2
  table_calendar: 3.0.8
  google_maps_flutter: ^2.6.0
  intl: ^0.17.0
  flutter_typeahead: ^4.0.0
  syncfusion_flutter_charts: ^21.2.4
  fl_chart: ^0.67.0
  charts_flutter: ^0.12.0
  mime: 1.0.0
  flutter_rating_bar: ^4.0.0
  rating_dialog: ^2.0.4
  url_launcher: ^6.1.12
  flutter_modular: ^5.0.0
  material_design_icons_flutter: ^5.0.0
  flutter_image_utilities: ^2.1.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/images_entree/
    - assets/images/offresSpecials/
    - assets/images/servicesPopulaires/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
